/*---------------------------------------------------------------------------------------------
 *  Primitive App Editor - roadmap Agent Tool
 *  Specification SSOT: docs/primitive-app-editor/Agent tool.md
 *--------------------------------------------------------------------------------------------*/

/**
 * roadmap.next `render_prompt` template, copied verbatim from
 * docs/primitive-app-editor/Agent tool.md (tool.commands.next.sequence[id=render_prompt].template).
 * A test asserts this stays identical to the specification.
 */
export const nextPromptTemplate = [
	'Implement the following roadmap bundle.',
	'',
	'## Bundle',
	'id: {{ bundle.id }}',
	'title: {{ bundle.title }}',
	'status: {{ bundle.status }}',
	'',
	'## Dependencies',
	'{{ bundle.depends_on }}',
	'',
	'## Current Evidence',
	'{{ bundle.evidence }}',
	'',
	'## Remaining Work',
	'{{ bundle.remaining }}',
	'',
	'## Implementation Specification',
	'{{#each implementation_specifications}}',
	'### {{ source }}',
	'{{ content }}',
	'',
	'{{/each}}',
	'',
	'## Boundary Constraints',
	'{{#each boundary_constraints}}',
	'### {{ source }}',
	'{{ content }}',
	'',
	'{{/each}}',
	'',
	'## Execution Rules',
	'- Implement only the selected bundle\'s implementation specifications.',
	'- Treat boundary references as constraints, not additional implementation scope.',
	'- Do not implement adjacent UI / Resolver / Runtime work merely because a boundary reference mentions it.',
	'- Keep all implementation consistent with supplied boundary constraints.',
	'- Preserve the Authority / Detail SSOT boundary identified by each source.',
	'- Do not infer requirements from specification files not supplied here.',
	'- If implementation or boundary references conflict, stop without implementing and report the conflict.',
	'- Do not modify roadmap.yaml directly.',
	'- Do not redefine depends_on.',
	'- Preserve existing implementation outside this bundle.',
	'- Verify the implementation before reporting completion.',
	'- When work is finished, call roadmap.complete.',
	'- Use status "implemented" only when the bundle is complete and verified.',
	'- Use status "partial" when work remains.',
	'- Record concrete evidence.',
	'- Record remaining work when status is "partial".',
	'',
	'## Bundle / Integration Rules',
	'- Bundle = minimum implementation unit. A bundle is not a permanently isolated, immutable product.',
	'- A later bundle can be the consumer that validates an earlier producer bundle through real usage.',
	'- When the selected bundle consumes an earlier implemented producer bundle, making that producer-consumer integration actually work is part of the selected bundle implementation.',
	'- If the selected consumer exposes missing behavior, an invalid contract, an integration defect, or an insufficient API, tool behavior, resolver, or registry in an earlier implemented producer, fix that producer as a required integration fix. Do not treat an earlier bundle as immutable merely because its status is `implemented`.',
	'- Allowed PR scope = selected bundle + required integration fixes. A required integration fix is limited to what is necessary to make the selected bundle work; it is not an unrelated refactor, adjacent feature implementation, or speculative cleanup.',
	'- Close the producer fix and selected consumer implementation in the same PR. Do not stop with only the producer fixed and the consumer disconnected, or use a consumer-only workaround that leaves the producer defect unresolved.',
	'- Do not complete an isolated small-grain implementation while required producer-consumer integration, actual consumer wiring, required integration fixes, or verification remains unresolved.',
	'- Future consumers do not need to be pre-validated. If a defect can only be exposed by a future consumer, address it when implementing that consumer bundle.',
	'- Required integration fixes do not expand boundary references into implementation scope. Boundary references remain constraints only, and unrelated UI / Resolver / Runtime work remains prohibited.',
	'- Preserve existing implementation and Authority / Detail SSOT semantics except for the minimum required integration fixes.',
	'',
	'## Completion / Summary Rules',
	'- Include required integration fixes in the selected bundle\'s verification, evidence, and final summary.',
	'- If an earlier producer bundle was modified as a required integration fix, report the producer bundle or affected implementation, the defect or missing behavior exposed by the selected consumer bundle, why the fix was required for the selected bundle, and verification proving that producer and consumer now work together.',
	'- If no earlier producer required an integration fix, report that briefly.',
	'- Record a required integration fix as evidence for the selected bundle. Do not change the earlier producer bundle\'s status because of that fix.',
	'',
].join('\n');
