/*---------------------------------------------------------------------------------------------
 *  Primitive App Editor - Editor built-in DDL and migrations (foundation.editor-ddl)
 *  Specification SSOT: docs/primitive-app-editor/App Editer.md (5. Built-in DDL)
 *--------------------------------------------------------------------------------------------*/

import { StringSHA1 } from '../../../../base/common/hash.js';
import { IProjectOpenContext, IProjectOpenSteps } from './projectDirectory.js';
import {
	assertProjectSqliteAccess,
	corePhysicalTableNameResolver,
	IProjectSqliteDatabase,
	IProjectSqliteStatements,
	ProjectSqliteAccessor,
	quoteIdentifier,
} from './projectSqlite.js';

/**
 * `Editor Built-in DDL` = the Editor fixed schema.
 *
 * `Editor -> DDL Resource Scan -> Schema Version Compare -> Unapplied Migration ->
 * SQLite Transaction -> Apply`. This module owns that pipeline and supplies the
 * `Editor DDL Scan` / `Schema Version Resolve` / `Migration Apply` steps of the project `Open`
 * lifecycle. `Registry DDL` (Application Physical Schema) is generated by the Registry Service
 * and is not part of this pipeline.
 */

// #region DDL Resource Scan

/** One `ddl/<NNN>_<name>.sql` resource. */
export interface IEditorDdlResource {
	readonly name: string;
	readonly sql: string;
}

/** A scanned resource: one migration of the Editor fixed schema. */
export interface IEditorDdlMigration {
	/** Schema version reached after applying this migration (`NNN`). */
	readonly version: number;
	/** Resource name, `<NNN>_<name>.sql`. */
	readonly name: string;
	readonly sql: string;
	/** SHA-1 of `sql`; an applied migration must never change. */
	readonly checksum: string;
}

export class EditorDdlError extends Error {
	constructor(message: string) {
		super(message);
		this.name = 'EditorDdlError';
	}
}

const resourceNamePattern = /^(\d{3})_[a-z][a-z0-9]*(?:_[a-z0-9]+)*\.sql$/;

/** Keywords that start a transaction control statement. */
const transactionControlKeywords: ReadonlySet<string> = new Set(['BEGIN', 'COMMIT', 'END', 'ROLLBACK', 'SAVEPOINT', 'RELEASE']);

/**
 * Leading keyword of every top-level statement in `sql`. Comments and quoted strings /
 * identifiers are ignored, and a `CREATE TRIGGER ... BEGIN ... END` body belongs to its
 * trigger statement, so its `BEGIN` / `END` are not statements of their own.
 */
function topLevelStatementKeywords(sql: string): readonly string[] {
	const tokens = sql
		.replace(/--[^\n]*|\/\*[\s\S]*?\*\/|'(?:[^']|'')*'|"(?:[^"]|"")*"|`(?:[^`]|``)*`|\[[^\]]*\]/g, ' ')
		.match(/[A-Za-z_][A-Za-z0-9_$]*|;/g) ?? [];
	const keywords: string[] = [];
	let statement: string[] = [];
	let inTriggerBody = false;
	let atBodyStatementStart = false;
	for (const token of tokens) {
		const word = token.toUpperCase();
		if (inTriggerBody) {
			if (word === ';') {
				atBodyStatementStart = true;
				continue;
			}
			if (atBodyStatementStart && word === 'END') {
				inTriggerBody = false;
			}
			atBodyStatementStart = false;
			continue;
		}
		if (word === ';') {
			statement = [];
			continue;
		}
		if (!statement.length) {
			keywords.push(word);
		}
		statement.push(word);
		if (word === 'BEGIN' && statement[0] === 'CREATE' && (statement[1] === 'TRIGGER' || statement[2] === 'TRIGGER')) {
			inTriggerBody = true;
			atBodyStatementStart = true;
		}
	}
	return keywords;
}

/**
 * Statements a built-in resource must not contain: the migration runner owns the SQLite
 * transaction, and the SQLite schema feature is not used (logical namespaces are flat
 * `<schema>__<table>` names).
 */
const forbiddenStatements: readonly { readonly test: (sql: string) => boolean; readonly reason: string }[] = Object.freeze([
	{ test: (sql: string) => topLevelStatementKeywords(sql).some(keyword => transactionControlKeywords.has(keyword)), reason: 'transaction control is owned by Migration Apply' },
	{ test: (sql: string) => /\b(ATTACH|DETACH)\b/i.test(sql), reason: 'the SQLite schema feature is not used' },
]);

export function computeEditorDdlChecksum(sql: string): string {
	const sha = new StringSHA1();
	sha.update(sql);
	return sha.digest();
}

/**
 * `DDL Resource Scan`: validates the resources and orders them by version. Versions start at 1
 * and are contiguous; names follow `<NNN>_<name>.sql`; every resource carries DDL.
 */
export function scanEditorDdlResources(resources: readonly IEditorDdlResource[]): readonly IEditorDdlMigration[] {
	const migrations: IEditorDdlMigration[] = [];
	for (const resource of resources) {
		const match = resourceNamePattern.exec(resource.name);
		if (!match) {
			throw new EditorDdlError(`Editor DDL resource name must match ${resourceNamePattern.source}: '${resource.name}'`);
		}
		if (!resource.sql.trim()) {
			throw new EditorDdlError(`Editor DDL resource '${resource.name}' is empty`);
		}
		for (const { test, reason } of forbiddenStatements) {
			if (test(resource.sql)) {
				throw new EditorDdlError(`Editor DDL resource '${resource.name}' is rejected: ${reason}`);
			}
		}
		migrations.push(Object.freeze({
			version: Number(match[1]),
			name: resource.name,
			sql: resource.sql,
			checksum: computeEditorDdlChecksum(resource.sql),
		}));
	}
	migrations.sort((a, b) => a.version - b.version);
	migrations.forEach((migration, index) => {
		if (migration.version !== index + 1) {
			throw new EditorDdlError(`Editor DDL versions must be contiguous from 001: expected ${String(index + 1).padStart(3, '0')}, got '${migration.name}'`);
		}
	});
	return Object.freeze(migrations);
}

// #endregion

// #region Schema Version Compare

/** Editor Internal Schema table recording applied built-in migrations (`editor.schema_version`). */
export const editorSchemaVersionPhysicalTable = corePhysicalTableNameResolver.resolve('editor', 'schema_version');

const schemaVersionTableDdl = `CREATE TABLE IF NOT EXISTS ${quoteIdentifier(editorSchemaVersionPhysicalTable)} (`
	+ '"version" INTEGER NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "checksum" TEXT NOT NULL, "appliedAt" TEXT NOT NULL)';

export interface IAppliedEditorDdlMigration {
	readonly version: number;
	readonly name: string;
	readonly checksum: string;
	readonly appliedAt: string;
}

export interface IEditorSchemaVersion {
	/** Version recorded in `project.sqlite`; `0` before any migration was applied. */
	readonly current: number;
	/** Latest version known to this Editor. */
	readonly target: number;
	readonly applied: readonly IAppliedEditorDdlMigration[];
	/** `Unapplied Migration`, in apply order. */
	readonly unapplied: readonly IEditorDdlMigration[];
}

export async function readAppliedEditorDdlMigrations(database: IProjectSqliteStatements): Promise<readonly IAppliedEditorDdlMigration[]> {
	const table = await database.get(`SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?`, [editorSchemaVersionPhysicalTable]);
	if (!table) {
		return Object.freeze([]);
	}
	const rows = await database.all(`SELECT "version", "name", "checksum", "appliedAt" FROM ${quoteIdentifier(editorSchemaVersionPhysicalTable)} ORDER BY "version"`);
	return Object.freeze(rows.map(row => Object.freeze({
		version: Number(row.version),
		name: String(row.name),
		checksum: String(row.checksum),
		appliedAt: String(row.appliedAt),
	})));
}

/**
 * `Schema Version Compare`: the applied migrations must be exactly the first versions of the
 * scanned resources, unchanged. A database written by a newer Editor (unknown version) or an
 * applied resource that was modified is rejected instead of being migrated.
 */
export function compareEditorSchemaVersion(migrations: readonly IEditorDdlMigration[], applied: readonly IAppliedEditorDdlMigration[]): IEditorSchemaVersion {
	applied.forEach((row, index) => {
		if (row.version !== index + 1) {
			throw new EditorDdlError(`project.sqlite Editor schema versions are not contiguous: expected ${index + 1}, found ${row.version}`);
		}
		const migration = migrations[index];
		if (!migration) {
			throw new EditorDdlError(`project.sqlite Editor schema version ${row.version} ('${row.name}') is newer than this Editor (latest ${migrations.length})`);
		}
		if (migration.name !== row.name || migration.checksum !== row.checksum) {
			throw new EditorDdlError(`Applied Editor DDL '${row.name}' (checksum ${row.checksum}) does not match resource '${migration.name}' (checksum ${migration.checksum})`);
		}
	});
	return Object.freeze({
		current: applied.length,
		target: migrations.length,
		applied,
		unapplied: Object.freeze(migrations.slice(applied.length)),
	});
}

export async function resolveEditorSchemaVersion(database: IProjectSqliteStatements, migrations: readonly IEditorDdlMigration[]): Promise<IEditorSchemaVersion> {
	assertProjectSqliteAccess(ProjectSqliteAccessor.Authoring);
	return compareEditorSchemaVersion(migrations, await readAppliedEditorDdlMigrations(database));
}

// #endregion

// #region SQLite Transaction -> Apply

/**
 * Applies every unapplied migration in one SQLite transaction and records each in
 * `editor__schema_version`. Any failure rolls back all of them. The schema version is compared
 * again inside the transaction so a concurrent writer cannot cause a double apply.
 */
export async function applyEditorDdlMigrations(database: IProjectSqliteDatabase, migrations: readonly IEditorDdlMigration[], resolved: IEditorSchemaVersion, now: () => Date = () => new Date()): Promise<readonly IAppliedEditorDdlMigration[]> {
	assertProjectSqliteAccess(ProjectSqliteAccessor.Authoring);
	if (!resolved.unapplied.length) {
		return Object.freeze([]);
	}
	return database.transaction(async tx => {
		const current = compareEditorSchemaVersion(migrations, await readAppliedEditorDdlMigrations(tx));
		if (current.current !== resolved.current) {
			throw new EditorDdlError(`project.sqlite Editor schema version changed during open: resolved ${resolved.current}, found ${current.current}`);
		}
		await tx.exec(schemaVersionTableDdl);
		const applied: IAppliedEditorDdlMigration[] = [];
		for (const migration of current.unapplied) {
			try {
				await tx.exec(migration.sql);
			} catch (error) {
				throw new EditorDdlError(`Editor DDL '${migration.name}' failed: ${error instanceof Error ? error.message : String(error)}`);
			}
			const row = Object.freeze({ version: migration.version, name: migration.name, checksum: migration.checksum, appliedAt: now().toISOString() });
			await tx.run(
				`INSERT INTO ${quoteIdentifier(editorSchemaVersionPhysicalTable)} ("version", "name", "checksum", "appliedAt") VALUES (?, ?, ?, ?)`,
				[row.version, row.name, row.checksum, row.appliedAt],
			);
			applied.push(row);
		}
		return Object.freeze(applied);
	});
}

// #endregion

// #region Open steps

/** Supplies the open `project.sqlite` (see `ProjectSqliteStorage`). */
export interface IEditorDdlDatabaseProvider {
	readonly database: IProjectSqliteDatabase;
}

/**
 * The `Editor DDL Scan` -> `Schema Version Resolve` -> `Migration Apply` steps of the project
 * `Open` lifecycle, run after `Create` / `Open` on the database opened by the storage step.
 * Each step requires the previous one; after `Migration Apply` the database is at the target
 * Editor schema version.
 */
export class EditorDdlMigrator implements Required<Pick<IProjectOpenSteps, 'editorDdlScan' | 'schemaVersionResolve' | 'migrationApply'>> {

	private _migrations: readonly IEditorDdlMigration[] | undefined;
	private _resolved: IEditorSchemaVersion | undefined;
	private _applied: readonly IAppliedEditorDdlMigration[] | undefined;

	constructor(
		private readonly storage: IEditorDdlDatabaseProvider,
		private readonly resources: readonly IEditorDdlResource[],
		private readonly now: () => Date = () => new Date(),
	) { }

	get migrations(): readonly IEditorDdlMigration[] | undefined { return this._migrations; }
	get resolved(): IEditorSchemaVersion | undefined { return this._resolved; }
	/** Migrations applied by the last `Migration Apply`; empty when the schema was already current. */
	get applied(): readonly IAppliedEditorDdlMigration[] | undefined { return this._applied; }

	async editorDdlScan(_context: IProjectOpenContext): Promise<void> {
		this._resolved = undefined;
		this._applied = undefined;
		this._migrations = scanEditorDdlResources(this.resources);
	}

	async schemaVersionResolve(_context: IProjectOpenContext): Promise<void> {
		if (!this._migrations) {
			throw new EditorDdlError('Schema Version Resolve requires Editor DDL Scan');
		}
		this._applied = undefined;
		this._resolved = await resolveEditorSchemaVersion(this.storage.database, this._migrations);
	}

	async migrationApply(_context: IProjectOpenContext): Promise<void> {
		if (!this._migrations || !this._resolved) {
			throw new EditorDdlError('Migration Apply requires Schema Version Resolve');
		}
		this._applied = await applyEditorDdlMigrations(this.storage.database, this._migrations, this._resolved, this.now);
	}
}

// #endregion
