/*---------------------------------------------------------------------------------------------
 *  Primitive App Editor - Editor built-in DDL resources (foundation.editor-ddl)
 *  Specification SSOT: docs/primitive-app-editor/App Editer.md (5. Built-in DDL)
 *--------------------------------------------------------------------------------------------*/

import { IEditorDdlResource } from './editorDdl.js';

/**
 * `ddl/`: the Editor fixed schema (`Editor Built-in DDL`), one resource per migration named
 * `<NNN>_<name>.sql`. The resources ship with the Editor code so every build target carries
 * them without copying loose `.sql` files.
 *
 * Applied resources are immutable: a schema change is a new resource with the next version.
 * Application Physical Schema (`Registry DDL`) is never declared here; it is generated by the
 * Registry Service.
 */
export const editorDdlResources: readonly IEditorDdlResource[] = Object.freeze([
	Object.freeze({
		name: '001_savedata.sql',
		// 32. Runtime Save Data / Save Identity: `logs.savedata` = Save Event only, `registry.current` = Save Data current
		// (UNIQUE key = UPSERT conflict target; saveId -> logs.savedata.uuid is a logical reference, no physical FK).
		sql: [
			'CREATE TABLE "logs__savedata" (',
			'\t"uuid" TEXT NOT NULL PRIMARY KEY,',
			'\t"timestamptz" TEXT NOT NULL',
			');',
			'CREATE TABLE "registry__current" (',
			'\t"uuid" TEXT NOT NULL PRIMARY KEY,',
			'\t"saveId" TEXT NOT NULL,',
			'\t"key" TEXT NOT NULL UNIQUE,',
			'\t"data" TEXT NOT NULL CHECK (json_valid("data"))',
			');',
		].join('\n'),
	}),
	Object.freeze({
		name: '002_table_registry.sql',
		// 8. table_registry: Registry authority of application tables (`schema` = logical namespace items | logs,
		// `columns` = one JSON list). Application Physical Schema generated from it is not declared here.
		sql: [
			'CREATE TABLE "registry__table_registry" (',
			'\t"uuid" TEXT NOT NULL PRIMARY KEY,',
			'\t"index" INTEGER NOT NULL,',
			'\t"schema" TEXT NOT NULL CHECK ("schema" IN (\'items\', \'logs\')),',
			'\t"name" TEXT NOT NULL,',
			'\t"label" TEXT NOT NULL,',
			'\t"columns" TEXT NOT NULL CHECK (json_valid("columns") AND json_type("columns") = \'array\'),',
			'\t"created_at" TEXT NOT NULL',
			');',
		].join('\n'),
	}),
]);
