/*---------------------------------------------------------------------------------------------
 *  Primitive App Editor - Editor built-in DDL resources (foundation.editor-ddl)
 *  Specification SSOT: docs/primitive-app-editor/App Editer.md (5. Built-in DDL)
 *--------------------------------------------------------------------------------------------*/

import { IEditorDdlResource } from './editorDdl.js';

/**
 * `ddl/`: the Editor fixed schema (`Editor Built-in DDL`), one resource per migration named
 * `<NNN>_<name>.sql`. The resources ship with the Editor code so every build target carries
 * them without copying loose `.sql` files.
 *
 * Applied resources are immutable: a schema change is a new resource with the next version.
 * Application Physical Schema (`Registry DDL`) is never declared here; it is generated by the
 * Registry Service.
 */
export const editorDdlResources: readonly IEditorDdlResource[] = Object.freeze([
	Object.freeze({
		name: '001_savedata.sql',
		// 32. Runtime Save Data / Save Identity: `logs.savedata` = Save Event only, `registry.current` = Save Data current
		// (UNIQUE key = UPSERT conflict target; saveId -> logs.savedata.uuid is a logical reference, no physical FK).
		sql: [
			'CREATE TABLE "logs__savedata" (',
			'\t"uuid" TEXT NOT NULL PRIMARY KEY,',
			'\t"timestamptz" TEXT NOT NULL',
			');',
			'CREATE TABLE "registry__current" (',
			'\t"uuid" TEXT NOT NULL PRIMARY KEY,',
			'\t"saveId" TEXT NOT NULL,',
			'\t"key" TEXT NOT NULL UNIQUE,',
			'\t"data" TEXT NOT NULL CHECK (json_valid("data"))',
			');',
		].join('\n'),
	}),
]);
